version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/*"
      - "/packages/*"
      - "/qa/tests/playwright"
    target-branch: "main"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "@strapi/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      strapi:
        patterns:
          - "@strapi/*"
        group-by: "dependency-name"
        update-types:
          - "minor"
          - "patch"
